language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
    - cd esp8266 ; npm install --only=dev ; cd ..
script:
    - build.sh
